scheduler: "DPF"
mode: "T"
T:
  - 1
release_period:
  - 24
timeout: 30
epsilon: 10
delta: 1e-5
rdp:
  - 1
n: 2
t: 20_000
elephants: "/home/kelly/PrivateKube/evaluation/macrobenchmark/workload/params/runs/event/elephants"
mice: "/home/kelly/PrivateKube/evaluation/macrobenchmark/workload/params/runs/event/mice-laplace"
mice_ratio: 0.5
m: 
  - 50
b: 10
