scheduler: "OVERFLOW_RELEVANCE"
mode: "T"
T:
  - 1
release_period:
  - 6.1
timeout: 100
epsilon: 10
delta: 1e-5
rdp:
  - 1
n: 1
t: 20000
elephants: "/home/kelly/PrivateKube/evaluation/macrobenchmark/workload/params/runs/event/elephants-demo"
mice: "/home/kelly/PrivateKube/evaluation/macrobenchmark/workload/params/runs/event/mice-demo"
mice_ratio: 0.5
m: 30
b: 2
