dataset: amazon
namespace: privacy-example
start_time: 0
end_time: 6
n_blocks: 6
epsilon: 1.0
delta: 1e-9
max_grad_norm: 1.0
device: cpu
max_text_len: 100
vocab_size: 2000
model: lstm
embedding_dim: 100
hidden_dim_1: 240
hidden_dim_2: 195
hidden_dim: 100
dropout: 0.25
task: sentiment
learning_rate: 0.01
dp: 1
user_level: 0
n_epochs: 3
batch_size: 64
noise: -1.0
timeframe_days: 0
learning_rate_scheduler: 1
n_workers: 2
