apiVersion: "columbia.github.com/v1"
kind: PrivacyBudgetClaim
metadata:
  name: claim-1
  namespace: privacy-example
spec:
  requests:
    - identifier: id-1
      allocateRequest:
        dataset: "amazon"
        conditions:
          - attribute: startTime
            numericValue: "0"
            operation: ">="
          - attribute: endTime
            numericValue: "200"
            operation: "<"
        minNumberOfBlocks: 1
        maxNumberOfBlocks: 1
        expectedBudget:
          constant:
            epsDel:
              epsilon: 0.01
              delta: 0.00000001
