apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: privacy-user-role
subjects:
  - kind: ServiceAccount
    name: default-editor
    namespace: kubeflow-<USER>
  - kind: User
    name: <KFNAME>-user@<PROJECT>.iam.gserviceaccount.com
    namespace: privacy-example
roleRef:
  kind: ClusterRole
  name: privacy-resource-admin
  apiGroup: rbac.authorization.k8s.io
