apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: testbudgets.columbia.github.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: columbia.github.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                budget:
                  type: object
                  properties:
                    epsilon:
                      type: number
                    delta:
                      type: number
                  oneOf:
                    - required: ["epsilon"]
                    - required: ["delta"]

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: testbudgets
    # singular name to be used as an alias on the CLI and for display
    singular: testbudget
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: TestBudget