# Model arguments
model: 
- "count_reviews"
- "count_per_category"
- "avg_rating_per_category"
- "avg_rating"
- "avg_tokens"
- "count_tokens"
- "std_tokens"
dp: 
- "non-dp"
- "event"
- "user-time"
- "user"

# Training arguments
batch_size: 2048

# Output arguments
log_path: ''
metrics_path: ''
model_path: ''

# Experiment arguments
dataset: amazon
python_path: statistics.py