# Model arguments
n_blocks:
  - 100
  - 200
  - 300
  - 400
  - 500
  - 1_000
  - 2_500
  - 5_000
  - 10_000
  - 15_000
  - 20_000
  - 25_000

epsilon:
  - 0.01
  - 0.05
  - 0.1

delta: 1e-10

# Training arguments
batch_size: 2048

# Output arguments
log_path: ""

# Experiment arguments
dataset: amazon
python_path: statistics.py
